id: IC1E2A24E
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T10:29:31+00:00'
last_modified: '2022-06-07T14:10:45.190781+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD105861
  title: སློབ་དཔོན་པདྨ་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་ཡིད་ཀྱི་མུན་སེལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    3B37:
      image_group_id: I1PD105863
      title: ''
      total_pages: 348
      order: 1
      base_file: 3B37.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
